# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='dashboard_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Dashboard Id'),
        ),
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='rule',
            name='panel_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Panel Id'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Rule Id'),
        ),
    ]
