# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_awscredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.GrafanaService'),
        ),
    ]
